**TACHE 6 : Etudier 3 éléments de symétrie différents, chacun pour 1 atome différent**

In [1]:
# Import 
import numpy as np
from pymatgen import Lattice, Structure, Molecule
from pymatgen.ext.matproj import MPRester
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.core.operations import *
from jupyter_jsmol.pymatgen import quick_view
from math import *

In [2]:
# Accéder aux données liées au cristal NaHF2 via l'API
with MPRester("gTFWb3O68X2aDOkOAmv") as m:
    # Structure for material id
    structure = m.get_structure_by_material_id("mp-27837")

Pour cet exercice, nous allons tout d'abord chercher, dans le fichier cif de la maille conventionnelle, l'opération de symétrie que l'on veut ainsi que la position de l'atome initial. Entuite, nous appliquons l'opération sur cet atome pour obtenir les coordonnées de l'atome final ainsi que la matrice de rotation et le vecteur de translation caractérisant l'opération. Puis nous ramenons l'atome final dans la maille initiale si nécessaire. Enfin, nous visualisons cette opération de symétrie dans la maille conventionnelle. Si la symétrie ne s'affiche pas, il faut alors exécuter une nouvelle fois la cellule de code. 

**Première opération de symétrie : (x+2/3, y+1/3, z+1/3)**

In [3]:
Sym1 = SymmOp.from_xyz_string("x+2/3, y+1/3, z+1/3")

# Coordonnées de l'atome de départ :
Na = [0.0, 0.0, 0.0]

# Application de l'opération de symétrie
print("Les coordonnées de l'atome Na initial sont:", Na, ".\n")
print("La matrice de rotation 'Rot' et le vecteur translation 'tau' de cette opération sont: \n",Sym1, "\n")
print("Cette opération de symétrie peut se caractériser par l'équation suivante:\n")

Les coordonnées de l'atome Na initial sont: [0.0, 0.0, 0.0] .

La matrice de rotation 'Rot' et le vecteur translation 'tau' de cette opération sont: 
 Rot:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tau
[0.66666667 0.33333333 0.33333333] 

Cette opération de symétrie peut se caractériser par l'équation suivante:



$$\begin{pmatrix}
    1 & 0 & 0 \\ 
    0 & 1 & 0 \\ 
    0 & 0 & 1 
\end{pmatrix} \begin{pmatrix}
    x \\ 
    y \\ 
    z 
\end{pmatrix} + \begin{pmatrix}
    2/3 \\ 
    1/3 \\ 
    1/3 
\end{pmatrix} = \begin{pmatrix}
    x + 2/3 \\ 
    y + 1/3 \\ 
    z + 1/3
\end{pmatrix}  $$

In [4]:
print("Les coordonnées de l'atome Na final sont:", Sym1.operate(Na), ".\n")
print("Cette opération est une translation de vecteur 'tau'.", "\n")
print("Voici la représentation de cette opération de symétrie sur l'atome Na numéro 1:", "\n")

view = quick_view(structure, "packed", conventional = True)
display(view)
view.script("draw symop 13 {atomno=1}")

Les coordonnées de l'atome Na final sont: [0.66666667 0.33333333 0.33333333] .

Cette opération est une translation de vecteur 'tau'. 

Voici la représentation de cette opération de symétrie sur l'atome Na numéro 1: 



JsmolView(layout=Layout(align_self='stretch', height='400px'))

**Deuxième opération de symétrie : (-x, -y, -z)**

In [6]:
Sym2 = SymmOp.from_xyz_string("-x, -y, -z")

# Coordonnées de l'atome de départ :
H = [0.0, 0.0, 0.5]

# Application de l'opération de symétrie
print("Les coordonnées de l'atome H initial sont:", H, ".\n")
print("La matrice de rotation 'Rot' et le vecteur translation 'tau' de cette opération sont: \n",Sym2, "\n")
print("Cette opération de symétrie peut se caractériser par l'équation suivante:\n")

Les coordonnées de l'atome H initial sont: [0.0, 0.0, 0.5] .

La matrice de rotation 'Rot' et le vecteur translation 'tau' de cette opération sont: 
 Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.] 

Cette opération de symétrie peut se caractériser par l'équation suivante:



$$\begin{pmatrix}
    -1 & 0 & 0 \\ 
    0 & -1 & 0 \\ 
    0 & 0 & -1 
\end{pmatrix} \begin{pmatrix}
    x \\ 
    y \\ 
    z 
\end{pmatrix} + \begin{pmatrix}
    0 \\ 
    0 \\ 
    0 
\end{pmatrix} = \begin{pmatrix}
    -x \\ 
    -y \\ 
    -z
\end{pmatrix}  $$

In [7]:
print("Les coordonnées de l'atome H final sont:", Sym2.operate(H), ".\n")
print("Cette opération est un inversion dont le centre est (0,0,0).", "\n")
print("On peut ramener ces coordonnées dans la maille initiale :", "[",Sym2.operate(H)[0], Sym2.operate(H)[1], Sym2.operate(H)[2]+1,"]", ".\n")
print("Voici la représentation de cette opération de symétrie sur l'atome H numéro 20:")
view = quick_view(structure, conventional = True)
display(view)
view.script("draw symop 2 {atomno=20}")

Les coordonnées de l'atome H final sont: [ 0.   0.  -0.5] .

Cette opération est un inversion dont le centre est (0,0,0). 

On peut ramener ces coordonnées dans la maille initiale : [ 0.0 0.0 0.5 ] .

Voici la représentation de cette opération de symétrie sur l'atome H numéro 20:


JsmolView(layout=Layout(align_self='stretch', height='400px'))

**Troisième opération de symétrie : (-y + 2/3, -x + 1/3, z + 1/3)**

In [9]:
Sym3 = SymmOp.from_xyz_string("-y + 2/3, -x + 1/3, z + 1/3")

# Coordonnées de l'atome de départ :
F = [0.0, 0.0, 0.41717400]

# Application de l'opération de symétrie
print("Les coordonnées de l'atome F initial sont:", F,".\n")
print("La matrice de rotation 'Rot' et le vecteur translation 'tau' de cette opération sont: \n",Sym3,"\n")
print("Cette opération de symétrie peut se caractériser par l'équation suivante:\n")

Les coordonnées de l'atome F initial sont: [0.0, 0.0, 0.417174] .

La matrice de rotation 'Rot' et le vecteur translation 'tau' de cette opération sont: 
 Rot:
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
tau
[0.66666667 0.33333333 0.33333333] 

Cette opération de symétrie peut se caractériser par l'équation suivante:



$$\begin{pmatrix}
    0 & -1 & 0 \\ 
    -1 & 0 & 0 \\ 
    0 & 0 & 1 
\end{pmatrix} \begin{pmatrix}
    x \\ 
    y \\ 
    z 
\end{pmatrix} + \begin{pmatrix}
    2/3 \\ 
    1/3 \\ 
    1/3 
\end{pmatrix} = \begin{pmatrix}
    -y + 2/3 \\ 
    -x + 1/3\\ 
    z + 1/3
\end{pmatrix}  $$

In [10]:
print("Les coordonnées de l'atome F final sont:", Sym3.operate(F),".\n")
print("Cette opération est une réflexion par rapport à un plan miroir perpendiculaire aux vecteurs de bases a et b suivie d'une translation de vecteur 'tau'.","\n")

print("Voici la représentation de cette opération de symétrie sur l'atome F numéro 3:")
print("La translation est faite avec un vecteur [-1/3, 1/3, 1/3], mais cela revient au même, en ramenant l'atome dans la maille initiale.")
view = quick_view(structure, conventional = True)
display(view)
view.script("draw symop 20 {atomno=3}")

Les coordonnées de l'atome F final sont: [0.66666667 0.33333333 0.75050733] .

Cette opération est une réflexion par rapport à un plan miroir perpendiculaire aux vecteurs de bases a et b suivie d'une translation de vecteur 'tau'. 

Voici la représentation de cette opération de symétrie sur l'atome F numéro 3:
La translation est faite avec un vecteur [-1/3, 1/3, 1/3], mais cela revient au même, en ramenant l'atome dans la maille initiale.


JsmolView(layout=Layout(align_self='stretch', height='400px'))